[package]
name = "main"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
passman = { path = "../passman"}
structopt = "0.3.22"
shellexpand = "2.1.0"
